version: '3.9'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/iot
    networks:
      - test_network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: iot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge

volumes:
  db-data: